spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/rbnbPerso?serverTimezone=UTC
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  port: 8081